# Generated by Django 4.2.6 on 2023-10-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mainheader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('buttontext', models.CharField(max_length=50)),
                ('buttoncolour', models.CharField(max_length=10)),
            ],
        ),
    ]
