# Generated by Django 4.2.6 on 2023-10-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainimg', models.ImageField(upload_to='myimage')),
                ('smallimg', models.ImageField(upload_to='myimage')),
            ],
        ),
    ]
