# Generated by Django 4.2.6 on 2023-10-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_mainimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subimg', models.ImageField(upload_to='myimage')),
            ],
        ),
    ]
