# Generated by Django 4.2.6 on 2023-10-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_buisness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buisnessdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='myimage')),
                ('heading', models.CharField(max_length=2000)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
    ]
