# Generated by Django 4.2.6 on 2023-10-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_whychooesus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slideimg_rightdescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='myimage')),
                ('heading1', models.CharField(max_length=2000)),
                ('description1', models.CharField(max_length=1000)),
                ('heading2', models.CharField(max_length=2000)),
                ('description2', models.CharField(max_length=1000)),
                ('heading3', models.CharField(max_length=2000)),
                ('description3', models.CharField(max_length=1000)),
                ('heading4', models.CharField(max_length=2000)),
                ('description4', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Slideimg_rightdescription_active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='myimage')),
                ('heading1', models.CharField(max_length=2000)),
                ('description1', models.CharField(max_length=1000)),
                ('heading2', models.CharField(max_length=2000)),
                ('description2', models.CharField(max_length=1000)),
                ('heading3', models.CharField(max_length=2000)),
                ('description3', models.CharField(max_length=1000)),
                ('heading4', models.CharField(max_length=2000)),
                ('description4', models.CharField(max_length=1000)),
            ],
        ),
    ]
