# Generated by Django 4.2.6 on 2023-10-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_slideimg_rightdescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartheading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=2000)),
            ],
        ),
    ]
