# Generated by Django 4.2.6 on 2023-10-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_cartheading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='myimage')),
                ('heading1', models.CharField(max_length=2000)),
                ('description1', models.CharField(max_length=1000)),
                ('buttontext', models.CharField(max_length=2000)),
                ('buttonlink', models.CharField(max_length=2000)),
            ],
        ),
    ]
