# Generated by Django 4.2.6 on 2023-10-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_featureheading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featurecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='myimage')),
                ('heading', models.CharField(max_length=2000)),
                ('shortdescription', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
