# Generated by Django 4.2.6 on 2023-10-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_prisingheading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prisingcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(max_length=2000)),
                ('heading2', models.CharField(max_length=2000)),
                ('paragraph', models.CharField(max_length=2000)),
                ('buttontext', models.CharField(max_length=2000)),
                ('buttonlink', models.CharField(max_length=2000)),
                ('featiurenameheading', models.CharField(max_length=2000)),
                ('features1', models.CharField(max_length=2000)),
                ('features2', models.CharField(max_length=2000)),
                ('features3', models.CharField(max_length=2000)),
                ('features4', models.CharField(blank=True, max_length=2000, null=True)),
                ('features5', models.CharField(blank=True, max_length=2000, null=True)),
                ('features6', models.CharField(blank=True, max_length=2000, null=True)),
                ('features7', models.CharField(blank=True, max_length=2000, null=True)),
                ('features8', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
