# Generated by Django 4.2.6 on 2023-10-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_prisingcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prisingcart2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(max_length=2000)),
                ('heading2', models.CharField(blank=True, max_length=2000, null=True)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Prisingcart2heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(max_length=2000)),
            ],
        ),
    ]
