# Generated by Django 4.2.6 on 2023-10-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_last'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutusstart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(max_length=2000)),
                ('heading2', models.CharField(max_length=2000)),
                ('img', models.ImageField(upload_to='myimage')),
                ('heading3', models.CharField(max_length=2000)),
                ('description', models.CharField(max_length=5000)),
                ('lastmassage', models.CharField(max_length=5000)),
            ],
        ),
    ]
