# Generated by Django 4.2.6 on 2023-10-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_aboutusstart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counternumber', models.CharField(max_length=2000)),
                ('countertext', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Counterheading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(max_length=2000)),
            ],
        ),
    ]
