# Generated by Django 4.2.6 on 2023-10-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_news_section_newssection_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ourteam_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=2000)),
                ('description', models.CharField(max_length=2000)),
                ('buttontext', models.CharField(max_length=2000)),
                ('buttonlink', models.CharField(max_length=2000)),
            ],
        ),
    ]
