# Generated by Django 4.2.6 on 2023-10-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_ourteam_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('position', models.CharField(max_length=2000)),
                ('img', models.ImageField(upload_to='myimage')),
                ('facebooklink', models.CharField(max_length=2000)),
                ('twiterlink', models.CharField(max_length=2000)),
                ('linkesinlink', models.CharField(max_length=2000)),
                ('instagramlink', models.CharField(max_length=2000)),
            ],
        ),
    ]
