# Generated by Django 4.2.6 on 2023-10-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_team_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=2000)),
                ('description', models.CharField(max_length=2000)),
                ('logo', models.ImageField(upload_to='myimage')),
                ('serchtitle', models.CharField(max_length=2000)),
                ('wavesimg', models.ImageField(upload_to='myimage')),
            ],
        ),
    ]
