# Generated by Django 4.2.6 on 2023-10-13 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_international_card_international_card_info_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='International_info1',
            new_name='International_infocard',
        ),
    ]
