# Generated by Django 4.2.6 on 2023-10-13 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_rename_international_info1_international_infocard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='International_service',
            new_name='International_service1',
        ),
    ]
