# Generated by Django 4.2.6 on 2023-10-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_ecommerce_card_ecommerce_card_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecommerce_serviceneww',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('button_text', models.CharField(max_length=500)),
                ('button_url', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='myimage')),
            ],
        ),
    ]
