# Generated by Django 4.2.6 on 2023-10-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trusted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500)),
            ],
        ),
    ]
